### ISSUE TITLE
Confint doesn't work with by=

### ISSUE THREAD

**Issue by eduardszoecs** [gavinsimpson/schoenberg#2]
Hi @gavinsimpson,

confint does not work with by= variables.

```r
library(mgcv)
devtools::install_github("gavinsimpson/schoenberg")
library(schoenberg) 
library(ggplot2)

dat <- gamSim(4, n = 1000)
mod <- gam(y ~ fac + s(x2, by = fac), data = dat)
plot(mod,pages=1)

ci <- confint(mod, parm = 'x2', type = "confidence")

ggplot(ci, aes(x = x2)) +
  geom_ribbon(aes(ymin = lower, ymax = upper), fill = 'grey80') +
  geom_line(aes(y = est)) +
  facet_wrap(~smooth)


ci2 <- confint(mod, parm = 'x2', type = "simultaneous") 
# Error in PredictMat(smooth, newx) : Can't find by variable
```

**Comment by eduardszoecs** [comment]
There are several parts that might lead to failure in `schoenberg`.
I tracked it to two changes.

1. confint-methods.R: Does not pass by-variables (leading to "by-variable not found")
2. evaluate_1d_smooth: Does not use the correct by-variable (leading to zero variance)

You can see those changes in [this commit](https://github.com/EDiLD/schoenberg/commit/c33426f142af34ed7870ea1cf14979fafd061457#diff-d53b25a1cd830d959ffb721516cfa779). Can you please check (not beeing familiar with the internals of `schoenberg` i tried my best. However, this solutions might not be correct. I didn't look at smooth_2d.

This works with it:

```r
ci2 <- confint(mod, parm = 'x2', type = "simultaneous") 

ggplot(ci2, aes(x = x2)) +
  geom_ribbon(aes(ymin = lower, ymax = upper), fill = 'grey80') +
  geom_line(aes(y = est)) +
  facet_wrap(~smooth)

dat <- rbind(data.frame(ci, type = 'confidence'),
             data.frame(ci2, type = 'simultaneous'))

ggplot(dat, aes(x = x2, color = type)) +
  geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.1) +
  geom_line(aes(y = est)) +
  facet_wrap(~smooth)
```

**Comment by gavinsimpson** [comment]
Thanks @EDiLD. This is both a bug and an enhancement effect. I haven't had chance to add `by` variable support to `confint` yet, but it also should stop if passed such a model and it doesn't.

Currently, I think only `draw()` handles `by` variables.
