### ISSUE TITLE
Need a new name for the package

### ISSUE THREAD

**Issue by meriops** [gavinsimpson/schoenberg#7]
FYI, I just noticed there's another package named `schoenberg` (after Arnold), already on cran...

**Comment by gavinsimpson** [comment]
Well that's annoying, but thanks for letting me know @meriops.

**Comment by gavinsimpson** [comment]
I have renamed the package *gratia* after the Latin derivation of "grace". Development will continue in [gavinsimpson/gratia](https://github.com/gavinsimpson/gratia)
